name: Data Indexing
on: [push]
jobs:
    Index-Spells:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: cd into directory
              run: cd ${{ github.workspace }}/data/spells/
            - name: index files
              run: ls >> index.html
